#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 27 10:58:51 2017

@author: jason
"""
#---IMPORTS---
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
#---MODIFIERS---
BOUNDS = (-10,10)
POINTS = 2**6
EPSILON = 2**-15